steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$_PROJECT_ID/payments:latest",
        "-f",
        "./payments/run/dockerfile.payments",
        ".",
      ]
images:
  - "gcr.io/$_PROJECT_ID/payments:latest"
