version: "3"

services:
  relaymanager-site1:
    build:
      context: .
      dockerfile: relaymanager/Dockerfile
    image: relaymanager:latest
    container_name: relaymanager-site1-container
    restart: always
    volumes:
      - ./config/site1:/app/config
      - ./secrets:/app/secrets

  relaymanager-site2:
    build:
      context: .
      dockerfile: relaymanager/Dockerfile
    image: relaymanager:latest
    container_name: relaymanager-site2-container
    restart: always
    volumes:
      - ./config/site2:/app/config
      - ./secrets:/app/secrets
