# Build stage
FROM golang:1.20.10 AS builder

WORKDIR /build

# Copy go mod and sum files
COPY ../go.mod ../go.sum ./

# Install dependencies
RUN go mod download

# Copy the source code
COPY . .

# Build the application
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o relaymanager ./relaymanager

# Final stage
FROM alpine:latest

WORKDIR /app

# Copy the binary from the build stage
COPY --from=builder /build/relaymanager .

# Set the binary as the entry point
ENTRYPOINT ["./relaymanager"]
