# Builder image
FROM golang:1.21 as builder
WORKDIR /app

# Copy the source code into the container
COPY . .

# Compile the application
# Disable CGO and statically link the application
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o payments ./payments/run

# Final image
FROM alpine:latest  
RUN apk --no-cache add ca-certificates

WORKDIR /root/

# Copy the binary from the builder image
COPY --from=builder /app/payments .

# Command to run
CMD ["./payments"]
