name: Deploy

on:
  push:
    branches:
      - main

env:
  DEPLOY_CONF: ${{ github.workspace }}/deploy.conf

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      project_id: ${{ steps.set-vars.outputs.project_id }}
      service_account: ${{ steps.set-vars.outputs.service_account }}
      workload_identity_provider: ${{ steps.set-vars.outputs.workload_identity_provider }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: List files
        run: |
          pwd
          ls -al
      - name: Set Environment Variables from deploy.conf
        id: set-vars
        run: |
          echo "Reading deploy.conf..."
          source $DEPLOY_CONF
          echo "Setting GitHub Actions outputs..."
          echo "::set-output name=project_id::$PROJECT_ID"
          echo "::set-output name=service_account::$SERVICE_ACCOUNT"
          echo "::set-output name=workload_identity_provider::$WORKLOAD_IDENTITY_PROVIDER"

  deploy:
    needs: setup
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - id: "Checkout"
        uses: actions/checkout@v3
      - id: "Auth"
        uses: "google-github-actions/auth@v1"
        with:
          workload_identity_provider: ${{ needs.setup.outputs.workload_identity_provider }}
          service_account: ${{ needs.setup.outputs.service_account }}
      - name: "Deploy"
        uses: "google-github-actions/deploy-cloudrun@v1"
        with:
          source: "."
          service: "nembot"
          region: "australia-southeast2"
