name: Deploy

on:
  push:
    branches:
      - main

env:
  DEPLOY_CONF: ${{ github.workspace }}/.github/workflows/deploy.conf

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      project_id: ${{ steps.set-vars.outputs.project_id }}
      service_account: ${{ steps.set-vars.outputs.service_account }}
      workload_identity_provider: ${{ steps.set-vars.outputs.workload_identity_provider }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Environment Variables from deploy.conf
        id: set-vars
        run: |
          echo "Reading deploy.conf..."
          source $DEPLOY_CONF
          echo "project_id=$PROJECT_ID" >> $GITHUB_OUTPUT
          echo "service_account=$SERVICE_ACCOUNT" >> $GITHUB_OUTPUT
          echo "workload_identity_provider=$WORKLOAD_IDENTITY_PROVIDER" >> $GITHUB_OUTPUT

  deploy-payment:
    needs: setup
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: "Auth"
        uses: "google-github-actions/auth@v1"
        with:
          workload_identity_provider: ${{ needs.setup.outputs.workload_identity_provider }}
          service_account: ${{ needs.setup.outputs.service_account }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ needs.setup.outputs.project_id }}
          # service_account_key: ${{ secrets.GCP_SA_KEY }}
          # export_default_credentials: true

      - name: Build and Push Docker image to Google Container Registry
        run: |
          gcloud builds submit --config cloudbuild.yaml --substitutions=_PROJECT_ID=${{ needs.setup.outputs.project_id }}

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy payments \
            --image gcr.io/${{ needs.setup.outputs.project_id }}/payments:latest \
            --platform managed \
            --region australia-southeast1 \
            --allow-unauthenticated

      # Deploy to Google Cloud Functions
      - name: Deploy to Google Cloud Functions
        run: |
          gcloud functions deploy OnUserCreated \
            --entry-point OnUserCreated \
            --runtime go121 \
            --trigger-event providers/firebase.auth/eventTypes/user.create \
            --source=./payments/functions \
            --region australia-southeast1
