name: Deploy firestore rules and indexes

on:
  push:
    branches:
      - main

env:
  DEPLOY_CONF: ${{ github.workspace }}/.github/workflows/deploy.conf

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      project_id: ${{ steps.set-vars.outputs.project_id }}
      service_account: ${{ steps.set-vars.outputs.service_account }}
      workload_identity_provider: ${{ steps.set-vars.outputs.workload_identity_provider }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Environment Variables from deploy.conf
        id: set-vars
        run: |
          echo "Reading deploy.conf..."
          source $DEPLOY_CONF
          echo "project_id=$PROJECT_ID" >> $GITHUB_OUTPUT
          echo "service_account=$SERVICE_ACCOUNT" >> $GITHUB_OUTPUT
          echo "workload_identity_provider=$WORKLOAD_IDENTITY_PROVIDER" >> $GITHUB_OUTPUT

  deploy:
    needs: setup
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: "Auth"
        uses: "google-github-actions/auth@v1"
        with:
          workload_identity_provider: ${{ needs.setup.outputs.workload_identity_provider }}
          service_account: ${{ needs.setup.outputs.service_account }}

      - name: Deploy using Firebase Action
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only firestore:rules,firestore:indexes
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: ${{ needs.setup.outputs.project_id }}
